apiVersion: v1
kind: Template
labels:
  app: platform-docs
  template: platform-docs
metadata:
  annotations:
    description: Cloud Services Platform documentation
  name: platform-docs
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: aletheia
    namespace: platform-docs
  spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 1
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - args:
              - aletheia
              - export
              - github:${PLATFORM_DOCS_SOURCE_REPO}
              - github:${PLATFORM_DOCS_TARGET_REPO}
              image: "${IMAGE_NAME}:${IMAGE_TAG}"
              imagePullPolicy: Always
              name: aletheia
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /etc/aletheia
                name: service-credentials
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
            - name: service-credentials
              secret:
                defaultMode: 410
                secretName: "${ALETHEIA_SECRET_NAME}"
    schedule: '@daily'
    successfulJobsHistoryLimit: 3
    suspend: false
parameters:
  - description: Platform Docs source repository reference
    name: PLATFORM_DOCS_SOURCE_REPO
    required: true
    value: RedHatInsights/platform-docs
  - description: Platform Docs target repository reference
    name: PLATFORM_DOCS_TARGET_REPO
    required: true
    value: RedHatInsights/platform-docs-build
  - description: Aletheia service credentials secret name
    name: ALETHEIA_SECRET_NAME
    required: true
    value: service-credentials
