apiVersion: v1
kind: Template
labels:
  app: platform-docs
  template: platform-docs
metadata:
  annotations:
    description: Cloud Services Platform documentation
  name: platform-docs
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: platform-docs
    name: platform-docs
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: platform-docs
    template:
      metadata:
        labels:
          name: platform-docs
      spec:
        containers:
        - image: "${IMAGE_NAME}:${IMAGE_TAG}"
          imagePullPolicy: Always
          name: platform-docs
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          hostname: platform-docs
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: platform-docs
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    selector:
      name: platform-docs
parameters:
  - description: Platform Docs image name
    name: IMAGE_NAME
    value: quay.io/cloudservices/platform-docs
    required: true
  - description: Platform Docs image tag
    name: IMAGE_TAG
    required: true
